services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    
  db:
    image: mysql:9.3.0
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 263500
      MYSQL_DATABASE: server
    ports:
      - 3306:3306
  app:
    build: .
    restart: always
    container_name: app
    ports:
      - 7788:3000
    depends_on:
      - redis
      - db

volumes:
  redis_volume_data:


  